package com.mycode.mybatis.dao;

import com.mycode.mybatis.model.ActivityIdConfigBean;

public interface ActivityIdConfigBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_id_config
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int deleteByPrimaryKey(String activityname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_id_config
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int insert(ActivityIdConfigBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_id_config
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int insertSelective(ActivityIdConfigBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_id_config
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    ActivityIdConfigBean selectByPrimaryKey(String activityname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_id_config
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int updateByPrimaryKeySelective(ActivityIdConfigBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_id_config
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int updateByPrimaryKey(ActivityIdConfigBean record);
}