package com.mycode.mybatis.dao;

import com.mycode.mybatis.model.PlayerHistoryRank;
import com.mycode.mybatis.model.PlayerHistoryRankKey;

public interface PlayerHistoryRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 10:47:31 CST 2017
     */
    int deleteByPrimaryKey(PlayerHistoryRankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 10:47:31 CST 2017
     */
    int insert(PlayerHistoryRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 10:47:31 CST 2017
     */
    int insertSelective(PlayerHistoryRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 10:47:31 CST 2017
     */
    PlayerHistoryRank selectByPrimaryKey(PlayerHistoryRankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 10:47:31 CST 2017
     */
    int updateByPrimaryKeySelective(PlayerHistoryRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 10:47:31 CST 2017
     */
    int updateByPrimaryKey(PlayerHistoryRank record);
}