package com.mycode.mybatis.dao;

import com.mycode.mybatis.model.PlayerHistoryRankBean;
import com.mycode.mybatis.model.PlayerHistoryRankBeanKey;

public interface PlayerHistoryRankBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int deleteByPrimaryKey(PlayerHistoryRankBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int insert(PlayerHistoryRankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int insertSelective(PlayerHistoryRankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    PlayerHistoryRankBean selectByPrimaryKey(PlayerHistoryRankBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int updateByPrimaryKeySelective(PlayerHistoryRankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_history_rank
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int updateByPrimaryKey(PlayerHistoryRankBean record);
}