package com.mycode.mybatis.dao;

import com.mycode.mybatis.model.TurntablePlayerRewardRecordBeanKey;

public interface TurntablePlayerRewardRecordBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_player_reward_record
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int deleteByPrimaryKey(TurntablePlayerRewardRecordBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_player_reward_record
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int insert(TurntablePlayerRewardRecordBeanKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turntable_player_reward_record
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    int insertSelective(TurntablePlayerRewardRecordBeanKey record);
}