package com.mycode.mybatis.model;

public class ActivityIdConfigBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_id_config.activityName
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private String activityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_id_config.activityID
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer activityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_id_config.activityName
     *
     * @return the value of activity_id_config.activityName
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public String getActivityname() {
        return activityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_id_config.activityName
     *
     * @param activityname the value for activity_id_config.activityName
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setActivityname(String activityname) {
        this.activityname = activityname == null ? null : activityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_id_config.activityID
     *
     * @return the value of activity_id_config.activityID
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_id_config.activityID
     *
     * @param activityid the value for activity_id_config.activityID
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }
}