package com.mycode.mybatis.model;

import java.util.Date;

public class PlayerHistoryRankKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_history_rank.roleId
     *
     * @mbg.generated Wed Aug 16 11:11:22 CST 2017
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_history_rank.date
     *
     * @mbg.generated Wed Aug 16 11:11:22 CST 2017
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_history_rank.type
     *
     * @mbg.generated Wed Aug 16 11:11:22 CST 2017
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_history_rank.roleId
     *
     * @return the value of player_history_rank.roleId
     *
     * @mbg.generated Wed Aug 16 11:11:22 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_history_rank.roleId
     *
     * @param roleid the value for player_history_rank.roleId
     *
     * @mbg.generated Wed Aug 16 11:11:22 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_history_rank.date
     *
     * @return the value of player_history_rank.date
     *
     * @mbg.generated Wed Aug 16 11:11:22 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_history_rank.date
     *
     * @param date the value for player_history_rank.date
     *
     * @mbg.generated Wed Aug 16 11:11:22 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_history_rank.type
     *
     * @return the value of player_history_rank.type
     *
     * @mbg.generated Wed Aug 16 11:11:22 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_history_rank.type
     *
     * @param type the value for player_history_rank.type
     *
     * @mbg.generated Wed Aug 16 11:11:22 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }
}