package com.mycode.mybatis.model;

import java.util.Date;

public class TurntablePlayerRewardRecordBeanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_reward_record.roleId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_reward_record.rewardId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer rewardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_reward_record.rewardDate
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Date rewarddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_reward_record.roleId
     *
     * @return the value of turntable_player_reward_record.roleId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_reward_record.roleId
     *
     * @param roleid the value for turntable_player_reward_record.roleId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_reward_record.rewardId
     *
     * @return the value of turntable_player_reward_record.rewardId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getRewardid() {
        return rewardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_reward_record.rewardId
     *
     * @param rewardid the value for turntable_player_reward_record.rewardId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRewardid(Integer rewardid) {
        this.rewardid = rewardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_reward_record.rewardDate
     *
     * @return the value of turntable_player_reward_record.rewardDate
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Date getRewarddate() {
        return rewarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_reward_record.rewardDate
     *
     * @param rewarddate the value for turntable_player_reward_record.rewardDate
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRewarddate(Date rewarddate) {
        this.rewarddate = rewarddate;
    }
}