package com.mycode.mybatis.model;

import java.util.Date;

public class TurntablePlayerItemBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_item.roleId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_item.roleName
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_item.itemCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer itemcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_item.consumeDiamond
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer consumediamond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_item.consumeDiamondTime
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Date consumediamondtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_item.shareCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer sharecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_player_item.shareTime
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Date sharetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_item.roleId
     *
     * @return the value of turntable_player_item.roleId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_item.roleId
     *
     * @param roleid the value for turntable_player_item.roleId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_item.roleName
     *
     * @return the value of turntable_player_item.roleName
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_item.roleName
     *
     * @param rolename the value for turntable_player_item.roleName
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_item.itemCount
     *
     * @return the value of turntable_player_item.itemCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getItemcount() {
        return itemcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_item.itemCount
     *
     * @param itemcount the value for turntable_player_item.itemCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setItemcount(Integer itemcount) {
        this.itemcount = itemcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_item.consumeDiamond
     *
     * @return the value of turntable_player_item.consumeDiamond
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getConsumediamond() {
        return consumediamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_item.consumeDiamond
     *
     * @param consumediamond the value for turntable_player_item.consumeDiamond
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setConsumediamond(Integer consumediamond) {
        this.consumediamond = consumediamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_item.consumeDiamondTime
     *
     * @return the value of turntable_player_item.consumeDiamondTime
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Date getConsumediamondtime() {
        return consumediamondtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_item.consumeDiamondTime
     *
     * @param consumediamondtime the value for turntable_player_item.consumeDiamondTime
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setConsumediamondtime(Date consumediamondtime) {
        this.consumediamondtime = consumediamondtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_item.shareCount
     *
     * @return the value of turntable_player_item.shareCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getSharecount() {
        return sharecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_item.shareCount
     *
     * @param sharecount the value for turntable_player_item.shareCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setSharecount(Integer sharecount) {
        this.sharecount = sharecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_player_item.shareTime
     *
     * @return the value of turntable_player_item.shareTime
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Date getSharetime() {
        return sharetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_player_item.shareTime
     *
     * @param sharetime the value for turntable_player_item.shareTime
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setSharetime(Date sharetime) {
        this.sharetime = sharetime;
    }
}