package com.mycode.mybatis.model;

public class TurntableRewardConfigBean extends TurntableRewardConfigBeanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_reward_config.name
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_reward_config.ratio
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer ratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_reward_config.leftCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer leftcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_reward_config.isReward
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer isreward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_reward_config.isBroadcast
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer isbroadcast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_reward_config.isDiamond
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer isdiamond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_reward_config.count
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_reward_config.name
     *
     * @return the value of turntable_reward_config.name
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_reward_config.name
     *
     * @param name the value for turntable_reward_config.name
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_reward_config.ratio
     *
     * @return the value of turntable_reward_config.ratio
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_reward_config.ratio
     *
     * @param ratio the value for turntable_reward_config.ratio
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRatio(Integer ratio) {
        this.ratio = ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_reward_config.leftCount
     *
     * @return the value of turntable_reward_config.leftCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getLeftcount() {
        return leftcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_reward_config.leftCount
     *
     * @param leftcount the value for turntable_reward_config.leftCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setLeftcount(Integer leftcount) {
        this.leftcount = leftcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_reward_config.isReward
     *
     * @return the value of turntable_reward_config.isReward
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getIsreward() {
        return isreward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_reward_config.isReward
     *
     * @param isreward the value for turntable_reward_config.isReward
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setIsreward(Integer isreward) {
        this.isreward = isreward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_reward_config.isBroadcast
     *
     * @return the value of turntable_reward_config.isBroadcast
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getIsbroadcast() {
        return isbroadcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_reward_config.isBroadcast
     *
     * @param isbroadcast the value for turntable_reward_config.isBroadcast
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setIsbroadcast(Integer isbroadcast) {
        this.isbroadcast = isbroadcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_reward_config.isDiamond
     *
     * @return the value of turntable_reward_config.isDiamond
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getIsdiamond() {
        return isdiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_reward_config.isDiamond
     *
     * @param isdiamond the value for turntable_reward_config.isDiamond
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setIsdiamond(Integer isdiamond) {
        this.isdiamond = isdiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_reward_config.count
     *
     * @return the value of turntable_reward_config.count
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_reward_config.count
     *
     * @param count the value for turntable_reward_config.count
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}