package com.mycode.mybatis.model;

public class TurntableActivityRewardBean extends TurntableActivityRewardBeanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.rewardName
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private String rewardname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.rewardCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer rewardcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.rewardLeftCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer rewardleftcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.rewardRatio
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer rewardratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.isBroadcast
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer isbroadcast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.isReward
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer isreward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.isDiamond
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer isdiamond;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.rewardName
     *
     * @return the value of turntable_activity_reward.rewardName
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public String getRewardname() {
        return rewardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.rewardName
     *
     * @param rewardname the value for turntable_activity_reward.rewardName
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRewardname(String rewardname) {
        this.rewardname = rewardname == null ? null : rewardname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.rewardCount
     *
     * @return the value of turntable_activity_reward.rewardCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getRewardcount() {
        return rewardcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.rewardCount
     *
     * @param rewardcount the value for turntable_activity_reward.rewardCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRewardcount(Integer rewardcount) {
        this.rewardcount = rewardcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.rewardLeftCount
     *
     * @return the value of turntable_activity_reward.rewardLeftCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getRewardleftcount() {
        return rewardleftcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.rewardLeftCount
     *
     * @param rewardleftcount the value for turntable_activity_reward.rewardLeftCount
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRewardleftcount(Integer rewardleftcount) {
        this.rewardleftcount = rewardleftcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.rewardRatio
     *
     * @return the value of turntable_activity_reward.rewardRatio
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getRewardratio() {
        return rewardratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.rewardRatio
     *
     * @param rewardratio the value for turntable_activity_reward.rewardRatio
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRewardratio(Integer rewardratio) {
        this.rewardratio = rewardratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.isBroadcast
     *
     * @return the value of turntable_activity_reward.isBroadcast
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getIsbroadcast() {
        return isbroadcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.isBroadcast
     *
     * @param isbroadcast the value for turntable_activity_reward.isBroadcast
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setIsbroadcast(Integer isbroadcast) {
        this.isbroadcast = isbroadcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.isReward
     *
     * @return the value of turntable_activity_reward.isReward
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getIsreward() {
        return isreward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.isReward
     *
     * @param isreward the value for turntable_activity_reward.isReward
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setIsreward(Integer isreward) {
        this.isreward = isreward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.isDiamond
     *
     * @return the value of turntable_activity_reward.isDiamond
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getIsdiamond() {
        return isdiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.isDiamond
     *
     * @param isdiamond the value for turntable_activity_reward.isDiamond
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setIsdiamond(Integer isdiamond) {
        this.isdiamond = isdiamond;
    }
}