package com.mycode.mybatis.model;

import java.util.Date;

public class TurntableActivityRewardBeanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.activityId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer activityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.rewardId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Integer rewardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turntable_activity_reward.rewardDate
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    private Date rewarddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.activityId
     *
     * @return the value of turntable_activity_reward.activityId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.activityId
     *
     * @param activityid the value for turntable_activity_reward.activityId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.rewardId
     *
     * @return the value of turntable_activity_reward.rewardId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Integer getRewardid() {
        return rewardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.rewardId
     *
     * @param rewardid the value for turntable_activity_reward.rewardId
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRewardid(Integer rewardid) {
        this.rewardid = rewardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turntable_activity_reward.rewardDate
     *
     * @return the value of turntable_activity_reward.rewardDate
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public Date getRewarddate() {
        return rewarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turntable_activity_reward.rewardDate
     *
     * @param rewarddate the value for turntable_activity_reward.rewardDate
     *
     * @mbg.generated Wed Aug 16 13:37:17 CST 2017
     */
    public void setRewarddate(Date rewarddate) {
        this.rewarddate = rewarddate;
    }
}